"""Initial migration.

Revision ID: 120f35f3b77d
Revises: 
Create Date: 2025-01-26 17:52:32.067598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120f35f3b77d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
